spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# security.oauth2.client.registration.github
spring.security.oauth2.client.registration.github.client-id=${SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET}

# security.oauth2.client.registration.google
spring.security.oauth2.client.registration.google.client-id=${SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}

# security.oauth2.client.registration.gitlab
spring.security.oauth2.client.registration.gitlab.client-id=${SECURITY_OAUTH2_CLIENT_REGISTRATION_GITLAB_CLIENT_ID}
spring.security.oauth2.client.registration.gitlab.client-secret=${SECURITY_OAUTH2_CLIENT_REGISTRATION_GITLAB_CLIENT_SECRET}
